name: sound_recording
description: Flutter sound recording plugin for DSP purposes, now supports android.
version: 0.0.2
repository: https://github.com/qiuxiang/flutter-sound-recording

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^4.2.3

flutter:
  plugin:
    platforms:
      android:
        package: qiuxiang.sound_recording
        pluginClass: SoundRecordingPlugin
      ios:
        pluginClass: SoundRecordingPlugin
