name: release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-java@v1
        with:
          java-version: 12
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - uses: bruceadams/get-release@v1.2.3
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Build
        run: |
          cd example
          flutter create .
          flutter build apk --target-platform android-arm64
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./example/build/app/outputs/flutter-apk/app-release.apk
          asset_name: example.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Release
        run: |
          echo '${{ secrets.CREDENTIALS_JSON }}' > $(which flutter | sed -r 's/bin\/flutter/.pub-cache\/credentials.json/')
          export version=$(echo ${{ steps.release.outputs.tag_name }} | sed s/v//)
          sed -i -r "s/version: .*/version: $version/" pubspec.yaml
          sed -i "1s/^/## $version\n\n${{ steps.release.outputs.body }}\n\n/" CHANGELOG.md
          git config --global user.name 7c00
          git config --global user.email i@7c00.cc
          git commit -am v$version
          git push
      - name: Publish
        run: flutter pub publish -f
